create extension if not exists pgcrypto;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text unique,
  phone text,
  role text not null default 'tenant' check (role in ('admin', 'owner', 'tenant')),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.is_admin(user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
      and role = 'admin'
      and is_active = true
  );
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role text;
begin
  requested_role := coalesce(new.raw_user_meta_data ->> 'preferred_role', 'tenant');

  if requested_role not in ('admin', 'owner', 'tenant') then
    requested_role := 'tenant';
  end if;

  insert into public.profiles (id, email, role, is_active)
  values (new.id, new.email, requested_role, true)
  on conflict (id) do update
  set
    email = excluded.email,
    role = excluded.role,
    updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_auth_user();

insert into public.profiles (id, email, role, is_active)
select
  id,
  email,
  case
    when raw_user_meta_data ->> 'preferred_role' in ('admin', 'owner', 'tenant')
      then raw_user_meta_data ->> 'preferred_role'
    else 'tenant'
  end,
  true
from auth.users
on conflict (id) do update
set
  email = excluded.email,
  role = excluded.role,
  updated_at = timezone('utc', now());

create table if not exists public.rooms (
  id integer primary key generated by default as identity,
  owner_id uuid references public.profiles(id) on delete set null,
  image text not null,
  cover_image_url text,
  price text not null,
  monthly_rent_paise integer check (monthly_rent_paise is null or monthly_rent_paise > 0),
  security_deposit_paise integer check (security_deposit_paise is null or security_deposit_paise >= 0),
  location text not null,
  city text not null,
  pincode text not null,
  type text not null check (type in ('Student', 'Professional')),
  status text not null default 'published' check (status in ('draft', 'published', 'occupied', 'inactive')),
  is_ready boolean not null default true,
  for_girls_only boolean not null default false,
  beds_available integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.rooms
  add column if not exists owner_id uuid references public.profiles(id) on delete set null,
  add column if not exists cover_image_url text,
  add column if not exists monthly_rent_paise integer check (monthly_rent_paise is null or monthly_rent_paise > 0),
  add column if not exists security_deposit_paise integer check (security_deposit_paise is null or security_deposit_paise >= 0),
  add column if not exists status text not null default 'published' check (status in ('draft', 'published', 'occupied', 'inactive'));

update public.rooms
set cover_image_url = image
where cover_image_url is null;

update public.rooms
set monthly_rent_paise = round((regexp_replace(price, '[^0-9.]', '', 'g')::numeric) * 100)::integer
where monthly_rent_paise is null
  and regexp_replace(price, '[^0-9.]', '', 'g') <> '';

create table if not exists public.room_images (
  id uuid primary key default gen_random_uuid(),
  room_id integer not null references public.rooms(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.property_leads (
  id uuid primary key default gen_random_uuid(),
  owner_name text not null,
  phone text not null,
  email text,
  property_type text not null,
  city text not null,
  pincode text not null,
  address text not null,
  expected_rent text,
  rooms_available text,
  notes text,
  status text not null default 'new' check (status in ('new')),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.room_bookings (
  id uuid primary key default gen_random_uuid(),
  room_id integer not null references public.rooms(id),
  owner_id uuid references public.profiles(id) on delete set null,
  room_snapshot jsonb not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_email text not null,
  assigned_tenant_id uuid references public.profiles(id) on delete set null,
  amount_paise integer not null check (amount_paise > 0),
  currency text not null default 'INR' check (currency in ('INR')),
  status text not null default 'created' check (status in ('created', 'paid')),
  booking_type text not null default 'reservation' check (booking_type in ('reservation')),
  booking_status text not null default 'initiated' check (booking_status in ('initiated', 'paid', 'cancelled', 'converted')),
  payment_status text not null default 'created' check (payment_status in ('created', 'paid', 'failed', 'refunded')),
  payment_type text not null default 'booking_reservation' check (payment_type in ('booking_reservation')),
  intent text not null default 'book-room' check (intent in ('book-room')),
  notes text,
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  paid_at timestamptz
);

alter table public.room_bookings
  add column if not exists owner_id uuid references public.profiles(id) on delete set null,
  add column if not exists assigned_tenant_id uuid references public.profiles(id) on delete set null,
  add column if not exists booking_type text not null default 'reservation' check (booking_type in ('reservation')),
  add column if not exists booking_status text not null default 'initiated' check (booking_status in ('initiated', 'paid', 'cancelled', 'converted')),
  add column if not exists payment_status text not null default 'created' check (payment_status in ('created', 'paid', 'failed', 'refunded')),
  add column if not exists payment_type text not null default 'booking_reservation' check (payment_type in ('booking_reservation')),
  add column if not exists notes text;

update public.room_bookings
set
  booking_status = case
    when status = 'paid' then 'paid'
    else 'initiated'
  end,
  payment_status = status,
  owner_id = coalesce(owner_id, (select owner_id from public.rooms where public.rooms.id = public.room_bookings.room_id))
where booking_status is null
   or payment_status is null
   or owner_id is null;

create table if not exists public.tenant_verifications (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.profiles(id) on delete cascade,
  document_type text,
  document_url text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  review_notes text,
  submitted_at timestamptz not null default timezone('utc', now()),
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tenant_room_assignments (
  id uuid primary key default gen_random_uuid(),
  room_id integer not null references public.rooms(id) on delete cascade,
  tenant_id uuid not null references public.profiles(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  booking_id uuid references public.room_bookings(id) on delete set null,
  start_date date not null,
  end_date date,
  status text not null default 'active' check (status in ('active', 'ended', 'pending_move_in')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.rent_invoices (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.tenant_room_assignments(id) on delete cascade,
  tenant_id uuid not null references public.profiles(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  room_id integer not null references public.rooms(id) on delete cascade,
  invoice_month date not null,
  rent_amount_paise integer not null check (rent_amount_paise > 0),
  due_date date not null,
  late_fee_paise integer not null default 0 check (late_fee_paise >= 0),
  total_amount_paise integer not null check (total_amount_paise > 0),
  status text not null default 'issued' check (status in ('draft', 'issued', 'paid', 'overdue', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.rent_payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.rent_invoices(id) on delete cascade,
  tenant_id uuid not null references public.profiles(id) on delete cascade,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  amount_paise integer not null check (amount_paise > 0),
  currency text not null default 'INR' check (currency in ('INR')),
  payment_method text,
  payment_provider text not null default 'razorpay',
  payment_type text not null default 'monthly_rent' check (payment_type in ('monthly_rent')),
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  status text not null default 'created' check (status in ('created', 'paid', 'failed', 'refunded')),
  paid_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.touch_updated_at();

drop trigger if exists set_rooms_updated_at on public.rooms;
create trigger set_rooms_updated_at
before update on public.rooms
for each row
execute function public.touch_updated_at();

drop trigger if exists set_room_bookings_updated_at on public.room_bookings;
create trigger set_room_bookings_updated_at
before update on public.room_bookings
for each row
execute function public.touch_updated_at();

drop trigger if exists set_tenant_verifications_updated_at on public.tenant_verifications;
create trigger set_tenant_verifications_updated_at
before update on public.tenant_verifications
for each row
execute function public.touch_updated_at();

drop trigger if exists set_tenant_room_assignments_updated_at on public.tenant_room_assignments;
create trigger set_tenant_room_assignments_updated_at
before update on public.tenant_room_assignments
for each row
execute function public.touch_updated_at();

drop trigger if exists set_rent_invoices_updated_at on public.rent_invoices;
create trigger set_rent_invoices_updated_at
before update on public.rent_invoices
for each row
execute function public.touch_updated_at();

drop trigger if exists set_rent_payments_updated_at on public.rent_payments;
create trigger set_rent_payments_updated_at
before update on public.rent_payments
for each row
execute function public.touch_updated_at();

create index if not exists idx_rooms_owner_id on public.rooms(owner_id);
create index if not exists idx_room_images_room_id on public.room_images(room_id);
create index if not exists idx_room_bookings_user_id on public.room_bookings(user_id);
create index if not exists idx_room_bookings_owner_id on public.room_bookings(owner_id);
create index if not exists idx_room_bookings_room_id on public.room_bookings(room_id);
create index if not exists idx_assignments_owner_id on public.tenant_room_assignments(owner_id);
create index if not exists idx_assignments_tenant_id on public.tenant_room_assignments(tenant_id);
create index if not exists idx_rent_invoices_tenant_id on public.rent_invoices(tenant_id);
create index if not exists idx_rent_payments_tenant_id on public.rent_payments(tenant_id);
create index if not exists idx_rent_payments_owner_id on public.rent_payments(owner_id);
create index if not exists idx_tenant_verifications_tenant_id on public.tenant_verifications(tenant_id);

alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.room_images enable row level security;
alter table public.property_leads enable row level security;
alter table public.room_bookings enable row level security;
alter table public.tenant_verifications enable row level security;
alter table public.tenant_room_assignments enable row level security;
alter table public.rent_invoices enable row level security;
alter table public.rent_payments enable row level security;

grant execute on function public.is_admin(uuid) to anon, authenticated;

grant select, insert on public.profiles to authenticated;
grant update on public.profiles to authenticated;

grant select on public.rooms to anon, authenticated;
grant insert, update, delete on public.rooms to authenticated;

grant select on public.room_images to anon, authenticated;
grant insert, update, delete on public.room_images to authenticated;

grant insert on public.property_leads to anon, authenticated;
grant select, update on public.property_leads to authenticated;

grant select, insert, update on public.room_bookings to authenticated;
grant select, insert, update on public.tenant_verifications to authenticated;
grant select, insert, update on public.tenant_room_assignments to authenticated;
grant select, insert, update on public.rent_invoices to authenticated;
grant select, insert, update on public.rent_payments to authenticated;

do $$
begin
  if exists (
    select 1
    from information_schema.sequences
    where sequence_schema = 'public'
      and sequence_name = 'rooms_id_seq'
  ) then
    grant usage, select on sequence public.rooms_id_seq to authenticated;
  end if;
end $$;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can create own profile" on public.profiles;
create policy "Users can create own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles"
on public.profiles
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read rooms" on public.rooms;
create policy "Public can read rooms"
on public.rooms
for select
to anon, authenticated
using (true);

drop policy if exists "Owners can read their rooms" on public.rooms;
create policy "Owners can read their rooms"
on public.rooms
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists "Admins can manage rooms" on public.rooms;
create policy "Admins can manage rooms"
on public.rooms
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read room images" on public.room_images;
create policy "Public can read room images"
on public.room_images
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can manage room images" on public.room_images;
create policy "Admins can manage room images"
on public.room_images
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can submit property leads" on public.property_leads;
create policy "Public can submit property leads"
on public.property_leads
for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can review property leads" on public.property_leads;
create policy "Admins can review property leads"
on public.property_leads
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can update property leads" on public.property_leads;
create policy "Admins can update property leads"
on public.property_leads
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Users can read own bookings" on public.room_bookings;
create policy "Users can read own bookings"
on public.room_bookings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own bookings" on public.room_bookings;
create policy "Users can create own bookings"
on public.room_bookings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own bookings" on public.room_bookings;
create policy "Users can update own bookings"
on public.room_bookings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Owners can read bookings for owned rooms" on public.room_bookings;
create policy "Owners can read bookings for owned rooms"
on public.room_bookings
for select
to authenticated
using (
  exists (
    select 1
    from public.rooms r
    where r.id = public.room_bookings.room_id
      and r.owner_id = auth.uid()
  )
);

drop policy if exists "Admins can manage bookings" on public.room_bookings;
create policy "Admins can manage bookings"
on public.room_bookings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Tenants can read own verifications" on public.tenant_verifications;
create policy "Tenants can read own verifications"
on public.tenant_verifications
for select
to authenticated
using (tenant_id = auth.uid());

drop policy if exists "Tenants can submit own verifications" on public.tenant_verifications;
create policy "Tenants can submit own verifications"
on public.tenant_verifications
for insert
to authenticated
with check (tenant_id = auth.uid());

drop policy if exists "Owners can read linked tenant verifications" on public.tenant_verifications;
create policy "Owners can read linked tenant verifications"
on public.tenant_verifications
for select
to authenticated
using (
  exists (
    select 1
    from public.tenant_room_assignments a
    where a.tenant_id = public.tenant_verifications.tenant_id
      and a.owner_id = auth.uid()
  )
);

drop policy if exists "Admins can manage verifications" on public.tenant_verifications;
create policy "Admins can manage verifications"
on public.tenant_verifications
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Tenants can read own assignments" on public.tenant_room_assignments;
create policy "Tenants can read own assignments"
on public.tenant_room_assignments
for select
to authenticated
using (tenant_id = auth.uid());

drop policy if exists "Owners can read own assignments" on public.tenant_room_assignments;
create policy "Owners can read own assignments"
on public.tenant_room_assignments
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists "Admins can manage assignments" on public.tenant_room_assignments;
create policy "Admins can manage assignments"
on public.tenant_room_assignments
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Tenants can read own invoices" on public.rent_invoices;
create policy "Tenants can read own invoices"
on public.rent_invoices
for select
to authenticated
using (tenant_id = auth.uid());

drop policy if exists "Owners can read own invoices" on public.rent_invoices;
create policy "Owners can read own invoices"
on public.rent_invoices
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists "Admins can manage invoices" on public.rent_invoices;
create policy "Admins can manage invoices"
on public.rent_invoices
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Tenants can read own rent payments" on public.rent_payments;
create policy "Tenants can read own rent payments"
on public.rent_payments
for select
to authenticated
using (tenant_id = auth.uid());

drop policy if exists "Tenants can create own rent payments" on public.rent_payments;
create policy "Tenants can create own rent payments"
on public.rent_payments
for insert
to authenticated
with check (tenant_id = auth.uid());

drop policy if exists "Tenants can update own rent payments" on public.rent_payments;
create policy "Tenants can update own rent payments"
on public.rent_payments
for update
to authenticated
using (tenant_id = auth.uid())
with check (tenant_id = auth.uid());

drop policy if exists "Owners can read own rent payments" on public.rent_payments;
create policy "Owners can read own rent payments"
on public.rent_payments
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists "Admins can manage rent payments" on public.rent_payments;
create policy "Admins can manage rent payments"
on public.rent_payments
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.rooms (
  id,
  image,
  cover_image_url,
  price,
  monthly_rent_paise,
  location,
  city,
  pincode,
  type,
  status,
  is_ready,
  for_girls_only,
  beds_available
)
values
  (1, '/images/room-1.jpg', '/images/room-1.jpg', '12,000', 1200000, 'Vijay Nagar, Indore', 'Indore', '452010', 'Student', 'published', true, true, 2),
  (2, '/images/room-2.jpg', '/images/room-2.jpg', '18,500', 1850000, 'Bhanwar Kuwa, Indore', 'Indore', '452001', 'Professional', 'published', true, false, 1),
  (3, '/images/room-3.jpg', '/images/room-3.jpg', '10,500', 1050000, 'Silicon City, Indore', 'Indore', '452012', 'Student', 'published', true, false, 3),
  (4, '/images/room-4.jpg', '/images/room-4.jpg', '22,000', 2200000, 'Dwarkapuri, Indore', 'Indore', '452009', 'Professional', 'published', true, true, 1),
  (5, '/images/room-1.jpg', '/images/room-1.jpg', '15,000', 1500000, 'Vaishali Nagar, Indore', 'Indore', '452021', 'Student', 'published', true, false, 2),
  (6, '/images/room-2.jpg', '/images/room-2.jpg', '20,000', 2000000, 'Palasia, Indore', 'Indore', '452001', 'Professional', 'published', true, false, 1)
on conflict (id) do update
set
  image = excluded.image,
  cover_image_url = excluded.cover_image_url,
  price = excluded.price,
  monthly_rent_paise = excluded.monthly_rent_paise,
  location = excluded.location,
  city = excluded.city,
  pincode = excluded.pincode,
  type = excluded.type,
  status = excluded.status,
  is_ready = excluded.is_ready,
  for_girls_only = excluded.for_girls_only,
  beds_available = excluded.beds_available,
  updated_at = timezone('utc', now());